### ISSUE TITLE
Alphabetical list for Codeigniter-Flexigrid

### ISSUE THREAD

**Issue by elixir1349** [sameersemna/ci-flexigrid#1]
Dear sameersemna,
I'm trying to integrate an alphabet list on the header in the form of javascript buttons like here: http://sanderkorvemaker.nl/test/flexigrid/ 

![alphabetical](https://cloud.githubusercontent.com/assets/3471861/6634260/a1ebe00a-c955-11e4-80ae-43f0ac7c8c66.png)

But for your project Codeigniter-Flexigrid I have problems to integrate them.

I find this tutorial http://cassianinet.blogspot.it/2012/02/flexigrid-con-codeigniter.html 
but I can't integrate alphabet javascript buttons in countries.php in your project. I miss something or I can't understand why can't work.
Can you help me to solve this problem or share me a working demo, please?

Thanks

**Comment by sameersemna** [comment]
Hi elixir,

Apologies for the delay, actually I just emigrated to Germany for a new job, so was not able to watch my public repos, I will definitely solve your problem and share a working demo with you.

Regards

**Comment by elixir1349** [comment]
Thank you very much, Good Luck for new Job!

**Comment by sameersemna** [comment]
Thanks, please star the repo if you like the work :)
